name: ci

on:
  push:
    branches:
      - "main"
env:
  DOCKER_USERNAME: '${{ secrets.DOCKER_USERNAME }}'
  DOCKER_REPO: '${{ secrets.DOCKER_REPO }}'

jobs:
  tests:
    uses: ./.github/workflows/integration-test.yaml
    secrets: inherit
  docker:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set enviroment
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.SHA_TAG }},${{ env.LATEST_TAG }}
        env:
          SHA_TAG: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.sha_short }}
          LATEST_TAG: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest