name: Generic CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  tests:
    name: Docker validation Test
    uses: ./.github/workflows/integration-test.yaml
    secrets: inherit
  dockerhub:
    name: DockerHub Repository Deployment
    needs: [tests]
    uses: ./.github/workflows/docker-cicd.yaml
    secrets: inherit
  digitalocean:
    name: Digitalocean Repository Deployment
    needs: [tests]
    uses: ./.github/workflows/digitalocean-cicd.yaml
    secrets: inherit